# SPDX-FileCopyrightText: 2023 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0

version: "3.4"
services:

  toldbehandling-rest:
    user: "75130:1000"  # Override in docker-compose.override.yml if your local user is different
    # user: "1000:1000"
    container_name: toldbehandling-rest
    image: toldbehandling-rest:latest
    build:
      context: .
      dockerfile: docker/Dockerfile_rest
    env_file:
      - ./dev-environment/rest.env
    volumes:
      - ./rest/:/app
      - ./data/er:/static/er
      - file-data:/upload
    depends_on:
      - toldbehandling-db
    environment:
      - MAKE_MIGRATIONS=true
      - MIGRATE=true
      - CREATE_USERS=true
      - TEST=false
    network_mode: "host"
    command: gunicorn -b 0.0.0.0:7000 project.wsgi:application --reload -w 1 --access-logfile - --error-logfile - --capture-output # reload on code changes

  toldbehandling-rest-cron:
    user: "75130:1000"  # Override in docker-compose.override.yml if your local user is different
    # user: "1000:1000"
    container_name: toldbehandling-rest-cron
    image: toldbehandling-rest:latest
    build:
      context: .
      dockerfile: docker/Dockerfile_rest
    env_file:
      - ./dev-environment/rest.env
    volumes:
      - ./rest/:/app
      - ./dev-environment/rest.crontab:/crontab
    depends_on:
      - toldbehandling-db
    environment:
      - MAKE_MIGRATIONS=false
      - MIGRATE=false
      - CREATE_USERS=false
      - CREATE_GROUPS=false
      - CREATE_POSTNUMRE=false
      - TEST=false
      - DUMMYDATA=false
    network_mode: "host"
    command: [ "supercronic", "/crontab" ]

  toldbehandling-ui:
    user: "75130:1000"  # Override in docker-compose.override.yml if your local user is different
    container_name: toldbehandling-ui
    image: toldbehandling-ui:latest
    build:
      context: .
      dockerfile: docker/Dockerfile_ui
    env_file:
      - ./dev-environment/ui.env
    depends_on:
      - toldbehandling-rest
      - toldbehandling-db
    volumes:
      - ./ui/:/app
      - ./told-common/told_common/:/app/told_common
      - file-data:/upload  # rw for at kunne teste; bør være ro i deployments
      - ./dev-environment/cert:/ssl:ro
    environment:
      - MAKE_MIGRATIONS=true
      - MIGRATE=true
      - TEST=false
    network_mode: "host"
    command: gunicorn -b 0.0.0.0:8000 project.wsgi:application --reload -w 1 --access-logfile - --error-logfile - --capture-output # reload on code changes

  toldbehandling-admin:
    user: "75130:1000"  # Override in docker-compose.override.yml if your local user is different
    container_name: toldbehandling-admin
    image: toldbehandling-admin:latest
    build:
      context: .
      dockerfile: docker/Dockerfile_admin
    env_file:
      - ./dev-environment/admin.env
    depends_on:
      - toldbehandling-ui
      - toldbehandling-db
    volumes:
      - ./admin/:/app
      - ./told-common/told_common/:/app/told_common
      - file-data:/upload  # rw for at kunne teste; bør være ro i deployments
    environment:
      - MAKE_MIGRATIONS=true
      - MIGRATE=true
      - TEST=false
    network_mode: "host"
    command: gunicorn -b 0.0.0.0:8001 project.wsgi:application --reload -w 1 --access-logfile - --error-logfile - --capture-output # reload on code changes

  toldbehandling-db:
    # Do not set `user` here
    container_name: toldbehandling-db
    image: postgres:13
    env_file:
      - ./dev-environment/rest.env
    volumes:
      - ./dev-environment/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
      - postgres-data:/var/lib/postgresql/data
    network_mode: "host"

  toldbehandling-er:
    user: "1000:1000"  # Override in docker-compose.override.yml if your local user is different
    container_name: toldbehandling-er
    image: toldbehandling-er:latest
    build:
      context: .
      dockerfile: docker/Dockerfile_er
    depends_on:
      - toldbehandling-db
    env_file:
      - ./dev-environment/rest.env
    volumes:
      - ./data/er:/doc
    network_mode: "host"

  toldbehandling-er-web:
    container_name: toldbehandling-er-web
    user: "1000:1000"
    image: halverneus/static-file-server:latest
    environment:
      - PORT=8002
      - URL_PREFIX=/er
    volumes:
      - ./data/er:/web:ro
    network_mode: "host"

  toldbehandling-test-idp:
    user: "1000:1000"  # Override in docker-compose.override.yml if your local user is different
    image: kenchan0130/simplesamlphp
    container_name: toldbehandling-test-idp
    network_mode: "host"
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: http://localhost:8000/saml/metadata/
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:8000/login/callback/
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost:8000/logout/callback/
      SIMPLESAMLPHP_IDP_CERTIFICATE: /var/www/simplesamlphp/cert/selfsigned.crt
      SIMPLESAMLPHP_IDP_PRIVATEKEY: /var/www/simplesamlphp/cert/selfsigned.key

    volumes:
      - ./dev-environment/cert/idp/selfsigned.crt:/var/www/simplesamlphp/cert/server.crt:ro
      - ./dev-environment/cert/idp/selfsigned.key:/var/www/simplesamlphp/cert/server.pem:ro
      - ./dev-idp/authsources.php:/var/www/simplesamlphp/config/authsources.php:ro
      - ./dev-idp/saml20-sp-remote.php:/var/www/simplesamlphp/metadata/saml20-sp-remote.php:ro


volumes:
  postgres-data:
  file-data:
