version: "3.4"
services:

  godsregistrering-rest:
    user: "75130:75130"  # Override in docker-compose.override.yml if your local user is different
    # user: "1000:1000"
    container_name: godsregistrering-rest
    image: godsregistrering-rest:latest
    build:
      context: .
      dockerfile: docker/Dockerfile_rest
    env_file:
      - ./dev-environment/rest.env
    volumes:
      - ./rest/:/app
      - ./data/er:/static/er
      - file-data:/upload
    depends_on:
      - godsregistrering-db
    environment:
      - MAKE_MIGRATIONS=true
      - MIGRATE=true
      - CREATE_USERS=true
      - TEST=true
    ports:
      - "7000:7000"
    command: gunicorn -b 0.0.0.0:7000 project.wsgi:application --reload -w 1 --access-logfile - --error-logfile - --capture-output # reload on code changes

  godsregistrering-ui:
    user: "1000:1000"  # Override in docker-compose.override.yml if your local user is different
    container_name: godsregistrering-ui
    image: godsregistrering-ui:latest
    build:
      context: .
      dockerfile: docker/Dockerfile_ui
    env_file:
      - ./dev-environment/ui.env
    depends_on:
      - godsregistrering-rest
    volumes:
      - ./ui/:/app
      - ./data/er:/static/er:ro
      - file-data:/upload  # rw for at kunne teste; bør være ro i deployments
    environment:
      - MAKE_MIGRATIONS=true
      - MIGRATE=true
    ports:
      - "8000:8000"
    command: gunicorn -b 0.0.0.0:8000 project.wsgi:application --reload -w 1 --access-logfile - --error-logfile - --capture-output # reload on code changes

  godsregistrering-db:
    # Do not set `user` here
    container_name: godsregistrering-db
    image: postgres:13
    env_file:
      - ./dev-environment/rest.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  godsregistrering-er:
    user: "1000:1000"  # Override in docker-compose.override.yml if your local user is different
    container_name: godsregistrering-er
    image: godsregistrering-er:latest
    build:
      context: .
      dockerfile: docker/Dockerfile_er
    depends_on:
      - godsregistrering-db
    env_file:
      - ./dev-environment/rest.env
    volumes:
      - ./data/er:/doc

volumes:
  postgres-data:
  file-data:
