version: "3.4"
services:

  toldbehandling-rest:
    user: "75130:1000"  # Override in docker-compose.override.yml if your local user is different
    # user: "1000:1000"
    container_name: toldbehandling-rest
    image: toldbehandling-rest:latest
    build:
      context: .
      dockerfile: docker/Dockerfile_rest
    env_file:
      - ./dev-environment/rest.env
    volumes:
      - ./rest/:/app
      - ./data/er:/static/er
      - file-data:/upload
    depends_on:
      - toldbehandling-db
    environment:
      - MAKE_MIGRATIONS=true
      - MIGRATE=true
      - CREATE_USERS=true
      - TEST=false
    ports:
      - "7000:7000"
    command: gunicorn -b 0.0.0.0:7000 project.wsgi:application --reload -w 1 --access-logfile - --error-logfile - --capture-output # reload on code changes

  toldbehandling-ui:
    user: "1000:1000"  # Override in docker-compose.override.yml if your local user is different
    container_name: toldbehandling-ui
    image: toldbehandling-ui:latest
    build:
      context: .
      dockerfile: docker/Dockerfile_ui
    env_file:
      - ./dev-environment/ui.env
    depends_on:
      - toldbehandling-rest
    volumes:
      - ./ui/:/app
      - ./data/er:/static/er:ro
      - file-data:/upload  # rw for at kunne teste; bør være ro i deployments
    environment:
      - MAKE_MIGRATIONS=true
      - MIGRATE=true
      - TEST=false
    ports:
      - "8000:8000"
    command: gunicorn -b 0.0.0.0:8000 project.wsgi:application --reload -w 1 --access-logfile - --error-logfile - --capture-output # reload on code changes

  toldbehandling-admin:
    user: "75060:1000"  # Override in docker-compose.override.yml if your local user is different
    container_name: toldbehandling-admin
    image: toldbehandling-admin:latest
    build:
      context: .
      dockerfile: docker/Dockerfile_admin
    env_file:
      - ./dev-environment/admin.env
    depends_on:
      - toldbehandling-ui
    volumes:
      - ./admin/:/app
      - ./data/er:/static/er:ro
      - file-data:/upload  # rw for at kunne teste; bør være ro i deployments
    environment:
      - MAKE_MIGRATIONS=true
      - MIGRATE=true
      - TEST=false
    ports:
      - "8001:8001"
    command: gunicorn -b 0.0.0.0:8001 project.wsgi:application --reload -w 1 --access-logfile - --error-logfile - --capture-output # reload on code changes


  toldbehandling-db:
    # Do not set `user` here
    container_name: toldbehandling-db
    image: postgres:13
    env_file:
      - ./dev-environment/rest.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  toldbehandling-er:
    user: "1000:1000"  # Override in docker-compose.override.yml if your local user is different
    container_name: toldbehandling-er
    image: toldbehandling-er:latest
    build:
      context: .
      dockerfile: docker/Dockerfile_er
    depends_on:
      - toldbehandling-db
    env_file:
      - ./dev-environment/rest.env
    volumes:
      - ./data/er:/doc

volumes:
  postgres-data:
  file-data:
