version = 1
SPDX-PackageName = "Toldbehandling"
SPDX-PackageSupplier = "Magenta ApS <info@magenta.dk>"

[[annotations]]
path = ["REUSE.toml", "told-common/**", "rest/**", "ui/**", "admin/**", "log/**", "dev-environment/**", "docker/**", "mockup/**", "dev-idp/**", "docker-compose.yml", "docker-compose.override.template.yml", "SUMMARY", "README.md", ".gitignore", ".gitlab-ci.yml", ".eslint/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Magenta ApS <info@magenta.dk>"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = "told-common/told_common/static/bootstrap/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2011-2023 The Bootstrap Authors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "told-common/told_common/static/bootstrap-table/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2012-2019 Zhixin Wen <wenzhixin2010@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "told-common/told_common/static/jquery/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "OpenJS Foundation and other contributors, https://openjsf.org/"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["told-common/told_common/static/font-awesome/webfonts/**.eot", "told-common/told_common/static/font-awesome/webfonts/**.ttf", "told-common/told_common/static/font-awesome/webfonts/**.woff", "told-common/told_common/static/font-awesome/webfonts/**.woff2"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2011-2021 @fontawesome (https://fontawesome.com)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "told-common/told_common/static/font-awesome/css/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2011-2021 @fontawesome (https://fontawesome.com)"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "told-common/told_common/static/font-awesome/webfonts/**.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2011-2021 @fontawesome (https://fontawesome.com)"
SPDX-License-Identifier = "CC-BY-4.0"
