from two_factor.plugins import registry as twofactor_registry
from django.utils.translation import gettext_lazy as _


class GeneratorMethod(twofactor_registry.GeneratorMethod):
    form_path = 'told_twofactor.forms.TOTPDeviceForm'
    code = "generator"

    def get_setup_forms(self, *args):
        from told_twofactor.forms import TOTPDeviceForm
        return {'generator': TOTPDeviceForm}

    def get_action(self, device):
        return _('Enter the token generated by your token generator')

    def get_verbose_action(self, device):
        return _('Please enter the token generated by your token generator.')


def update_registry():
    twofactor_registry.registry.unregister("generator")
    twofactor_registry.registry.register(GeneratorMethod())
    print("registry updated")
