# Generated by Django 4.2.1 on 2023-06-22 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afgiftstabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gyldig_fra', models.DateField(auto_now_add=True)),
                ('gyldig_til', models.DateField(blank=True, null=True)),
                ('kladde', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-gyldig_fra', '-gyldig_til'],
            },
        ),
        migrations.CreateModel(
            name='Vareafgiftssats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vareart', models.CharField(max_length=300)),
                ('afgiftsgruppenummer', models.PositiveIntegerField()),
                ('enhed', models.CharField(choices=[('ant', 'Antal'), ('kg', 'Kilogram'), ('l', 'Liter'), ('pct', 'Procent af fakturabeløb')], default='ant', max_length=3)),
                ('afgiftssats', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('afgiftstabel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sats.afgiftstabel')),
            ],
            options={
                'ordering': ['afgiftsgruppenummer'],
            },
        ),
        migrations.AddConstraint(
            model_name='vareafgiftssats',
            constraint=models.UniqueConstraint(fields=('afgiftstabel', 'vareart'), name='vareart_constraint'),
        ),
        migrations.AddConstraint(
            model_name='vareafgiftssats',
            constraint=models.UniqueConstraint(fields=('afgiftstabel', 'afgiftsgruppenummer'), name='afgiftsgruppenummer_constraint'),
        ),
    ]
