# Generated by Django 4.2.2 on 2023-12-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vareafgiftssats',
            name='synlig_privat',
            field=models.BooleanField(default=False, verbose_name='Vareafgiftssatsen kan bruges af private'),
        ),
    ]
