# Generated by Django 4.2.2 on 2023-09-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sats', '0002_remove_vareafgiftssats_afgiftsgruppenummer_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afgiftstabel',
            name='gyldig_fra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='afgiftstabel',
            constraint=models.CheckConstraint(check=models.Q(('kladde', True), ('gyldig_fra__isnull', False), _connector='OR'), name='kladde_or_has_gyldig_fra'),
        ),
    ]
