# Generated by Django 4.2.2 on 2024-01-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sats', '0002_vareafgiftssats_har_privat_tillægsafgift_alkohol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afgiftstabel',
            name='gyldig_fra',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='afgiftstabel',
            name='gyldig_til',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
