# SPDX-FileCopyrightText: 2023 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0

# Generated by Django 4.2.2 on 2023-09-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sats', '0003_alter_afgiftstabel_gyldig_fra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vareafgiftssats',
            old_name='vareart',
            new_name='vareart_da',
        ),
    ]
