# Generated by Django 4.2.2 on 2024-01-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sats', '0003_alter_afgiftstabel_gyldig_fra_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afgiftstabel',
            options={'ordering': ['-gyldig_fra', '-gyldig_til'], 'permissions': [('approve_afgiftstabel', 'Kan godkende afgiftstabel / sætte kladde til False')]},
        ),
    ]
