# Generated by Django 4.2.2 on 2023-11-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sats', '0004_rename_vareart'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vareafgiftssats',
            name='vareart_constraint',
        ),
        migrations.AddField(
            model_name='vareafgiftssats',
            name='vareart_kl',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddConstraint(
            model_name='vareafgiftssats',
            constraint=models.UniqueConstraint(fields=('afgiftstabel', 'vareart_da'), name='vareart_constraint_da'),
        ),
        migrations.AddConstraint(
            model_name='vareafgiftssats',
            constraint=models.UniqueConstraint(fields=('afgiftstabel', 'vareart_kl'), name='vareart_constraint_kl'),
        ),
    ]
