# Generated by Django 4.2.24 on 2025-10-08 09:22

from django.db import migrations, models

def populate_indførselstilladelser(apps, schema_editor):
    Vareafgiftssats = apps.get_model('sats', 'Vareafgiftssats')
    for sats in Vareafgiftssats.objects.all():
        if sats.kræver_indførselstilladelse:
            if "ETHANOLHOLDIGE DRIKKEVARER" in sats.vareart_da:
                sats.kræver_indførselstilladelse_alkohol = sats.kræver_indførselstilladelse
            else:
                sats.kræver_indførselstilladelse_tobak = sats.kræver_indførselstilladelse
            sats.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sats', '0004_alter_afgiftstabel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vareafgiftssats',
            name='kræver_indførselstilladelse_alkohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vareafgiftssats',
            name='kræver_indførselstilladelse_tobak',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(populate_indførselstilladelser),
        migrations.RemoveField(
            model_name='vareafgiftssats',
            name='kræver_indførselstilladelse',
        ),
    ]
