# Generated by Django 4.2.11 on 2025-05-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sats', '0004_alter_afgiftstabel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vareafgiftssats',
            name='kræver_indførselstilladelse',
        ),
        migrations.AddField(
            model_name='vareafgiftssats',
            name='alkohol_indførselstilladelse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vareafgiftssats',
            name='tobak_indførselstilladelse',
            field=models.BooleanField(default=False),
        ),
    ]
