# Generated by Django 4.2.2 on 2023-11-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sats', '0005_remove_vareafgiftssats_vareart_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vareafgiftssats',
            name='vareart_kl',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
