# Generated by Django 4.2.1 on 2023-06-22 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afsender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(db_index=True, max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('postnummer', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('by', models.CharField(db_index=True, max_length=20)),
                ('postbox', models.CharField(blank=True, max_length=10, null=True)),
                ('telefon', models.CharField(max_length=12)),
                ('cvr', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
            ],
            options={
                'ordering': ['navn'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Modtager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(db_index=True, max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('postnummer', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('by', models.CharField(db_index=True, max_length=20)),
                ('postbox', models.CharField(blank=True, max_length=10, null=True)),
                ('telefon', models.CharField(max_length=12)),
                ('cvr', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('kreditordning', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['navn'],
                'abstract': False,
            },
        ),
    ]
