# Generated by Django 4.2.2 on 2023-07-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktør', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modtager',
            name='indførselstilladelse',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
