# Generated by Django 4.2.2 on 2023-10-24 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktør', '0002_modtager_indførselstilladelse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afsender',
            name='cvr',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AlterField(
            model_name='modtager',
            name='cvr',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
