# Generated by Django 4.2.2 on 2023-10-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktør', '0002_modtager_indførselstilladelse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modtager',
            name='indførselstilladelse',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
