# Generated by Django 4.2.2 on 2024-01-26 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktør', '0002_alter_afsender_options_alter_modtager_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speditør',
            fields=[
                ('cvr', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('navn', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
