# Generated by Django 4.2.2 on 2024-02-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aktør', '0003_speditør'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='afsender',
            name='aktuel_afsender_har_telefon',
        ),
        migrations.RemoveConstraint(
            model_name='modtager',
            name='aktuel_modtager_har_telefon',
        ),
    ]
