# Generated by Django 4.2.2 on 2023-11-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktør', '0003_alter_afsender_cvr_alter_modtager_cvr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modtager',
            name='indførselstilladelse',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
