# Generated by Django 4.2.2 on 2023-11-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aktør', '0004_alter_modtager_indførselstilladelse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modtager',
            name='indførselstilladelse',
        ),
    ]
