# Generated by Django 4.2.2 on 2024-02-12 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktør', '0004_remove_afsender_aktuel_afsender_har_telefon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afsender',
            name='postnummer',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AlterField(
            model_name='modtager',
            name='postnummer',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
