# Generated by Django 4.2.2 on 2023-11-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktør', '0005_remove_modtager_indførselstilladelse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afsender',
            name='by',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='modtager',
            name='by',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
