# Generated by Django 4.2.11 on 2024-11-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktør', '0006_afsender_eksplicit_stedkode_afsender_postnummer_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afsender',
            name='land',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modtager',
            name='land',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
