# SPDX-FileCopyrightText: 2023 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0

FROM python:3.10
ENV PYTHONUNBUFFERED=1
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN mkdir /app && \
#gid/uid from salt
groupadd -g 75130 -r toldbehandling && \
groupadd -g 75100 -r certificate_exporter && \
useradd -u 75130 --no-log-init -r -g toldbehandling -G certificate_exporter toldbehandling
COPY rest/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
# hadolint ignore=DL3008
RUN apt-get update && \
    apt-get install -y --no-install-recommends gettext python3-distutils graphviz && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir /upload && chown -R toldbehandling /upload
USER toldbehandling
COPY ./docker/entrypoint_rest.sh /entrypoint.sh
COPY --chown=toldbehandling:toldbehandling ./rest /app
EXPOSE 8000
ENTRYPOINT ["/entrypoint.sh"]
WORKDIR /app
CMD ["gunicorn","-b","0.0.0.0:8000","project.wsgi:application","-w 4","--timeout 120","--error-logfile","-","--capture-output"]
