# Generated by Django 4.2.2 on 2023-11-30 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from datetime import date
import forsendelse.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postforsendelse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forsendelsestype', models.CharField(choices=[('S', 'Skib'), ('F', 'Fly')], default='S', max_length=1)),
                ('afgangsdato', models.DateField(default=date.today)),
                ('postforsendelsesnummer', models.CharField(db_index=True, max_length=20)),
                ('afsenderbykode', models.CharField(db_index=True, max_length=4)),
                ('oprettet_af', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['postforsendelsesnummer'],
            },
        ),
        migrations.CreateModel(
            name='Fragtforsendelse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forsendelsestype', models.CharField(choices=[('S', 'Skib'), ('F', 'Fly')], default='S', max_length=1)),
                ('afgangsdato', models.DateField(default=date.today)),
                ('fragtbrevsnummer', models.CharField(db_index=True, max_length=20)),
                ('forbindelsesnr', models.CharField(db_index=True, max_length=100)),
                ('fragtbrev', models.FileField(blank=True, null=True, upload_to=forsendelse.models.fragtbrev_upload_to)),
                ('oprettet_af', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fragtbrevsnummer'],
            },
        ),
    ]
