# Generated by Django 4.2.2 on 2024-01-22 09:25

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('forsendelse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragtforsendelse',
            name='kladde',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postforsendelse',
            name='kladde',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fragtforsendelse',
            name='afgangsdato',
            field=models.DateField(default=django.utils.datetime_safe.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='fragtforsendelse',
            name='forbindelsesnr',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fragtforsendelse',
            name='fragtbrevsnummer',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postforsendelse',
            name='afgangsdato',
            field=models.DateField(default=django.utils.datetime_safe.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='postforsendelse',
            name='afsenderbykode',
            field=models.CharField(db_index=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='postforsendelse',
            name='postforsendelsesnummer',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='fragtforsendelse',
            constraint=models.CheckConstraint(check=models.Q(('fragtbrevsnummer__isnull', False), ('kladde', True), _connector='OR'), name='aktuel_har_fragtbrevsnummer'),
        ),
        migrations.AddConstraint(
            model_name='fragtforsendelse',
            constraint=models.CheckConstraint(check=models.Q(('forbindelsesnr__isnull', False), ('kladde', True), _connector='OR'), name='aktuel_har_forbindelsesnr'),
        ),
        migrations.AddConstraint(
            model_name='postforsendelse',
            constraint=models.CheckConstraint(check=models.Q(('postforsendelsesnummer__isnull', False), ('kladde', True), _connector='OR'), name='aktuel_har_postforsendelsesnummer'),
        ),
        migrations.AddConstraint(
            model_name='postforsendelse',
            constraint=models.CheckConstraint(check=models.Q(('afsenderbykode__isnull', False), ('kladde', True), _connector='OR'), name='aktuel_har_afsenderbykode'),
        ),
    ]
