# Generated by Django 4.2.2 on 2024-01-23 09:03

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('forsendelse', '0002_fragtforsendelse_kladde_postforsendelse_kladde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragtforsendelse',
            name='afgangsdato',
            field=models.DateField(blank=True, default=django.utils.datetime_safe.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='fragtforsendelse',
            name='forbindelsesnr',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fragtforsendelse',
            name='fragtbrevsnummer',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postforsendelse',
            name='afgangsdato',
            field=models.DateField(blank=True, default=django.utils.datetime_safe.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='postforsendelse',
            name='afsenderbykode',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='postforsendelse',
            name='postforsendelsesnummer',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
