# Generated by Django 4.2.2 on 2023-11-02 11:47

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('forsendelse', '0002_fragtforsendelse_opretter_postforsendelse_opretter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragtforsendelse',
            name='afgangsdato',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
        ),
        migrations.AddField(
            model_name='postforsendelse',
            name='afgangsdato',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
        ),
    ]
