# Generated by Django 4.2.11 on 2025-07-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forsendelse', '0003_alter_fragtforsendelse_afgangsdato_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fragtforsendelse',
            name='aktuel_har_fragtbrevsnummer',
        ),
        migrations.RemoveConstraint(
            model_name='fragtforsendelse',
            name='aktuel_har_forbindelsesnr',
        ),
        migrations.RemoveConstraint(
            model_name='postforsendelse',
            name='aktuel_har_postforsendelsesnummer',
        ),
        migrations.RemoveConstraint(
            model_name='postforsendelse',
            name='aktuel_har_afsenderbykode',
        ),
        migrations.RemoveField(
            model_name='fragtforsendelse',
            name='kladde',
        ),
        migrations.RemoveField(
            model_name='postforsendelse',
            name='kladde',
        ),
    ]
