# Generated by Django 4.2.2 on 2023-09-27 07:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndberetterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpr', models.PositiveIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(101000000), django.core.validators.MaxValueValidator(3112999999)])),
                ('cvr', models.PositiveIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indberetter_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
