# Generated by Django 4.2.2 on 2023-11-02 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postnummer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postnummer', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('navn', models.CharField(max_length=100)),
                ('dage', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
