# Generated by Django 4.2.2 on 2023-11-28 10:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0013_alter_historicalvarelinje_fakturabeløb_and_more'),
        ('common', '0002_postnummer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EboksBesked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=500)),
                ('cpr', models.PositiveIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(101000000), django.core.validators.MaxValueValidator(3112999999)])),
                ('cvr', models.PositiveIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('pdf', models.BinaryField()),
                ('sendt', models.BooleanField(default=False)),
                ('oprettet', models.DateTimeField(auto_now_add=True)),
                ('opdateret', models.DateTimeField(auto_now=True)),
                ('forsøg', models.PositiveSmallIntegerField(default=0)),
                ('afgiftsanmeldelse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anmeldelse.afgiftsanmeldelse')),
            ],
        ),
        migrations.CreateModel(
            name='EboksDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oprettet', models.DateTimeField(auto_now_add=True)),
                ('opdateret', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(max_length=40)),
                ('status_code', models.PositiveSmallIntegerField(null=True)),
                ('status_message', models.CharField(max_length=500, null=True)),
                ('besked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.eboksbesked')),
            ],
        ),
        migrations.AddConstraint(
            model_name='eboksbesked',
            constraint=models.CheckConstraint(check=models.Q(('cpr__isnull', False), ('cvr__isnull', False), _connector='OR'), name='has_cpr_or_cvr'),
        ),
    ]
