# Generated by Django 4.2.2 on 2024-02-19 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_eboksbesked_privat_afgiftsanmeldelse'),
    ]

    operations = [
        migrations.AddField(
            model_name='postnummer',
            name='stedkode',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
