# Generated by Django 4.2.2 on 2024-02-15 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_eboksbesked_privat_afgiftsanmeldelse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stedkode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('navn', models.CharField(max_length=100)),
            ],
        ),
    ]
