# Generated by Django 4.2.11 on 2024-05-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_postnummer_stedkode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indberetterprofile',
            name='api_key',
            field=models.CharField(editable=False, max_length=128, unique=True),
        ),
    ]
