# Generated by Django 4.2.2 on 2024-02-19 07:31

from django.db import migrations
from django.core import management

def update_postcodes(apps, schema_editor):
    management.call_command('create_postnumre')


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_indberetterprofile_api_key'),
    ]

    operations = [
        migrations.RunPython(update_postcodes),
    ]
