# Generated by Django 4.2.2 on 2023-06-28 10:24

import anmeldelse.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forsendelse', '0001_initial'),
        ('sats', '0001_initial'),
        ('aktør', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afgiftsanmeldelse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anmeldelsesnummer', models.PositiveBigIntegerField(unique=True)),
                ('leverandørfaktura_nummer', models.CharField(db_index=True, max_length=20)),
                ('leverandørfaktura', models.FileField(blank=True, null=True, upload_to=anmeldelse.models.afgiftsanmeldelse_upload_to)),
                ('modtager_betaler', models.BooleanField(default=False)),
                ('indførselstilladelse', models.CharField(db_index=True, max_length=20)),
                ('afgift_total', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('betalt', models.BooleanField(default=False)),
                ('dato', models.DateField(auto_now_add=True, db_index=True)),
                ('afsender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afgiftsanmeldelser', to='aktør.afsender')),
                ('fragtforsendelse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afgiftsanmeldelse', to='forsendelse.fragtforsendelse')),
                ('modtager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afgiftsanmeldelser', to='aktør.modtager')),
                ('postforsendelse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afgiftsanmeldelse', to='forsendelse.postforsendelse')),
            ],
            options={
                'ordering': ['dato'],
            },
        ),
        migrations.CreateModel(
            name='Varelinje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kvantum', models.PositiveIntegerField()),
                ('fakturabeløb', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('afgiftsbeløb', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('afgiftsanmeldelse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anmeldelse.afgiftsanmeldelse')),
                ('afgiftssats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sats.vareafgiftssats')),
            ],
            options={
                'ordering': ['afgiftssats'],
            },
        ),
    ]
