# SPDX-FileCopyrightText: 2023 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0

# Generated by Django 4.2.2 on 2023-08-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afgiftsanmeldelse',
            name='anmeldelsesnummer',
        ),
    ]
