# Generated by Django 4.2.2 on 2023-12-06 12:55

import anmeldelse.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anmeldelse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivatAfgiftsanmeldelse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oprettet', models.DateTimeField(auto_now_add=True)),
                ('cpr', models.BigIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(101000000), django.core.validators.MaxValueValidator(3112999999)], verbose_name='CPR-nummer')),
                ('anonym', models.BooleanField(db_index=True, default=False)),
                ('navn', models.CharField(db_index=True, max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('postnummer', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('by', models.CharField(db_index=True, max_length=50)),
                ('telefon', models.CharField(max_length=12)),
                ('bookingnummer', models.CharField(max_length=128, verbose_name='Bookingnummer udstedt af speditør')),
                ('leverandørfaktura_nummer', models.CharField(max_length=20, verbose_name='Varefakturanummer udstedt af forhandler')),
                ('indførselstilladelse', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nummer på senest udstedte indførselstilladelse')),
                ('indleveringsdato', models.DateField()),
                ('leverandørfaktura', models.FileField(blank=True, null=True, upload_to=anmeldelse.models.privatafgiftsanmeldelse_upload_to)),
                ('status', models.CharField(choices=[('ny', 'ny'), ('afvist', 'afvist'), ('godkendt', 'godkendt'), ('afsluttet', 'afsluttet')], default='ny')),
            ],
        ),
        migrations.AlterField(
            model_name='varelinje',
            name='afgiftsanmeldelse',
            field=simple_history.models.HistoricForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anmeldelse.afgiftsanmeldelse'),
        ),
        migrations.AddField(
            model_name='privatafgiftsanmeldelse',
            name='oprettet_af',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_afgiftsanmeldelser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvarelinje',
            name='privatafgiftsanmeldelse',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='anmeldelse.privatafgiftsanmeldelse'),
        ),
        migrations.AddField(
            model_name='varelinje',
            name='privatafgiftsanmeldelse',
            field=simple_history.models.HistoricForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='anmeldelse.privatafgiftsanmeldelse'),
        ),
        migrations.AddConstraint(
            model_name='varelinje',
            constraint=models.CheckConstraint(check=models.Q(('afgiftsanmeldelse__isnull', False), ('privatafgiftsanmeldelse__isnull', False), _connector='OR'), name='afgiftsanmeldelse_has_one'),
        ),
        migrations.AddConstraint(
            model_name='varelinje',
            constraint=models.CheckConstraint(check=models.Q(('afgiftsanmeldelse__isnull', True), ('privatafgiftsanmeldelse__isnull', True), _connector='OR'), name='afgiftsanmeldelse_only_one'),
        ),
        migrations.RenameField(
            model_name='prismeresponse',
            old_name='invoice_date',
            new_name='delivery_date'
        ),
    ]
