# Generated by Django 4.2.2 on 2023-12-13 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anmeldelse', '0002_privatafgiftsanmeldelse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afgiftsanmeldelse',
            name='oprettet_på_vegne_af',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afgiftsanmeldelser_på_vegne_af', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalafgiftsanmeldelse',
            name='oprettet_på_vegne_af',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
