# SPDX-FileCopyrightText: 2023 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0

# Generated by Django 4.2.2 on 2023-08-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0002_remove_afgiftsanmeldelse_anmeldelsesnummer'),
    ]

    operations = [
        migrations.AddField(
            model_name='afgiftsanmeldelse',
            name='godkendt',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
