# Generated by Django 4.2.2 on 2023-12-15 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anmeldelse', '0002_privatafgiftsanmeldelse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatafgiftsanmeldelse',
            name='oprettet_på_vegne_af',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_afgiftsanmeldelser_på_vegne_af', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalvarelinje',
            name='afgiftsanmeldelse',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='anmeldelse.afgiftsanmeldelse'),
        ),
        migrations.AlterField(
            model_name='privatafgiftsanmeldelse',
            name='status',
            field=models.CharField(choices=[('ny', 'ny'), ('annulleret', 'annulleret'), ('afvist', 'afvist'), ('godkendt', 'godkendt'), ('afsluttet', 'afsluttet')], default='ny'),
        ),
        migrations.AlterField(
            model_name='varelinje',
            name='afgiftsanmeldelse',
            field=simple_history.models.HistoricForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='anmeldelse.afgiftsanmeldelse'),
        ),
    ]
