# Generated by Django 4.2.2 on 2023-12-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0003_afgiftsanmeldelse_oprettet_på_vegne_af_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afgiftsanmeldelse',
            name='toldkategori',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Toldkategori'),
        ),
        migrations.AddField(
            model_name='historicalafgiftsanmeldelse',
            name='toldkategori',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Toldkategori'),
        ),
    ]
