# Generated by Django 4.2.2 on 2024-01-05 12:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0003_privatafgiftsanmeldelse_oprettet_på_vegne_af_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afgiftsanmeldelse',
            name='afgift_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='historicalafgiftsanmeldelse',
            name='afgift_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
    ]
