# SPDX-FileCopyrightText: 2023 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0

# Generated by Django 4.2.2 on 2023-09-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0003_afgiftsanmeldelse_godkendt'),
    ]

    operations = [
        migrations.AddField(
            model_name='varelinje',
            name='mængde',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='varelinje',
            name='kvantum',
        ),
        migrations.AddField(
            model_name='varelinje',
            name='antal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='varelinje',
            old_name='afgiftssats',
            new_name='vareafgiftssats'
        ),
        migrations.AlterModelOptions(
            name='varelinje',
            options={'ordering': ['vareafgiftssats']},
        ),
    ]
