# Generated by Django 4.2.2 on 2024-01-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0004_alter_afgiftsanmeldelse_afgift_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afgiftsanmeldelse',
            name='dato',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalafgiftsanmeldelse',
            name='dato',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
    ]
