# SPDX-FileCopyrightText: 2023 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0

# Generated by Django 4.2.2 on 2023-09-28 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anmeldelse', '0004_varelinje_mængde_alter_varelinje_kvantum'),
    ]

    operations = [
        migrations.AddField(
            model_name='afgiftsanmeldelse',
            name='oprettet_af',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afgiftsanmeldelser', to=settings.AUTH_USER_MODEL),
        ),
    ]
