# Generated by Django 4.2.2 on 2023-10-06 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0005_afgiftsanmeldelse_opretter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afgiftsanmeldelse',
            options={'ordering': ['id']},
        ),
    ]
