# Generated by Django 4.2.2 on 2024-01-24 13:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anmeldelse', '0006_historicalvarelinje_kladde_varelinje_kladde_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPrivatAfgiftsanmeldelse',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('oprettet', models.DateTimeField(blank=True, editable=False)),
                ('cpr', models.BigIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(101000000), django.core.validators.MaxValueValidator(3112999999)], verbose_name='CPR-nummer')),
                ('anonym', models.BooleanField(db_index=True, default=False)),
                ('navn', models.CharField(db_index=True, max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('postnummer', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('by', models.CharField(db_index=True, max_length=50)),
                ('telefon', models.CharField(max_length=12)),
                ('bookingnummer', models.CharField(max_length=128, verbose_name='Bookingnummer udstedt af speditør')),
                ('leverandørfaktura_nummer', models.CharField(max_length=20, verbose_name='Varefakturanummer udstedt af forhandler')),
                ('indførselstilladelse', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nummer på senest udstedte indførselstilladelse')),
                ('indleveringsdato', models.DateField()),
                ('leverandørfaktura', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ny', 'ny'), ('annulleret', 'annulleret'), ('afvist', 'afvist'), ('godkendt', 'godkendt'), ('afsluttet', 'afsluttet')], default='ny')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical privat afgiftsanmeldelse',
                'verbose_name_plural': 'historical privat afgiftsanmeldelses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='notat',
            name='privatafgiftsanmeldelse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='anmeldelse.privatafgiftsanmeldelse'),
        ),
        migrations.AlterField(
            model_name='notat',
            name='afgiftsanmeldelse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='anmeldelse.afgiftsanmeldelse'),
        ),
        migrations.AddConstraint(
            model_name='notat',
            constraint=models.CheckConstraint(check=models.Q(('afgiftsanmeldelse__isnull', False), ('privatafgiftsanmeldelse__isnull', False), _connector='OR'), name='notat_has_one_anmeldelse'),
        ),
        migrations.AddConstraint(
            model_name='notat',
            constraint=models.CheckConstraint(check=models.Q(('afgiftsanmeldelse__isnull', True), ('privatafgiftsanmeldelse__isnull', True), _connector='OR'), name='notat_only_one_anmeldelse'),
        ),
        migrations.AddField(
            model_name='historicalprivatafgiftsanmeldelse',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprivatafgiftsanmeldelse',
            name='oprettet_af',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprivatafgiftsanmeldelse',
            name='oprettet_på_vegne_af',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
