# Generated by Django 4.2.2 on 2023-10-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0007_alter_varelinje_afgiftsanmeldelse_notat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notat',
            name='index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
