# Generated by Django 4.2.2 on 2024-01-26 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aktør', '0003_speditør'),
        ('anmeldelse', '0007_historicalprivatafgiftsanmeldelse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afgiftsanmeldelse',
            name='fuldmagtshaver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aktør.speditør'),
        ),
        migrations.AddField(
            model_name='historicalafgiftsanmeldelse',
            name='fuldmagtshaver',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='aktør.speditør'),
        ),
    ]
