# Generated by Django 4.2.2 on 2023-11-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0008_notat_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afgiftsanmeldelse',
            name='indførselstilladelse',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalafgiftsanmeldelse',
            name='indførselstilladelse',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
