# Generated by Django 4.2.2 on 2024-01-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('anmeldelse', '0006_historicalvarelinje_kladde_varelinje_kladde_and_more'),
        # ('anmeldelse', '0007_historicalprivatafgiftsanmeldelse_and_more'),
        ('anmeldelse', '0008_afgiftsanmeldelse_fuldmagtshaver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afgiftsanmeldelse',
            name='betales_af',
            field=models.CharField(blank=True, choices=[(None, 'Blank'), ('afsender', 'Afsender'), ('modtager', 'Modtager'), ('indberetter', 'Indberetter')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalafgiftsanmeldelse',
            name='betales_af',
            field=models.CharField(blank=True, choices=[(None, 'Blank'), ('afsender', 'Afsender'), ('modtager', 'Modtager'), ('indberetter', 'Indberetter')], default=None, max_length=20, null=True),
        ),
    ]
