# Generated by Django 4.2.2 on 2023-11-03 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0009_alter_afgiftsanmeldelse_indførselstilladelse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvarelinje',
            name='mængde',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='varelinje',
            name='mængde',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
