# Generated by Django 4.2.2 on 2024-01-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0010_afgiftsanmeldelse_modtager_betaler_to_betales_af'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='afgiftsanmeldelse',
            constraint=models.CheckConstraint(check=models.Q(('leverandørfaktura__isnull', False), ('status', 'kladde'), _connector='OR'), name='aktuel_har_leverandørfaktura'),
        ),
    ]
