# Generated by Django 4.2.2 on 2023-11-10 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0010_alter_historicalvarelinje_mængde_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrismeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_id', models.BigIntegerField()),
                ('tax_notification_number', models.BigIntegerField()),
                ('invoice_date', models.DateTimeField()),
                ('afgiftsanmeldelse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anmeldelse.afgiftsanmeldelse')),
            ],
        ),
    ]
