# Generated by Django 4.2.2 on 2023-11-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0011_prismeresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afgiftsanmeldelse',
            name='godkendt',
        ),
        migrations.RemoveField(
            model_name='historicalafgiftsanmeldelse',
            name='godkendt',
        ),
        migrations.AddField(
            model_name='afgiftsanmeldelse',
            name='status',
            field=models.CharField(choices=[('ny', 'ny'), ('afvist', 'afvist'), ('godkendt', 'godkendt'), ('afsluttet', 'afsluttet')], default='ny'),
        ),
        migrations.AddField(
            model_name='historicalafgiftsanmeldelse',
            name='status',
            field=models.CharField(choices=[('ny', 'ny'), ('afvist', 'afvist'), ('godkendt', 'godkendt'), ('afsluttet', 'afsluttet')], default='ny'),
        ),
    ]
