# Generated by Django 4.2.2 on 2024-02-09 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0011_afgiftsanmeldelse_aktuel_har_leverandørfaktura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvarelinje',
            name='mængde',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='varelinje',
            name='mængde',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
