# Generated by Django 4.2.2 on 2023-11-24 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0012_remove_afgiftsanmeldelse_godkendt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvarelinje',
            name='fakturabeløb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='varelinje',
            name='fakturabeløb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
