# Generated by Django 4.2.2 on 2023-11-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0013_alter_historicalvarelinje_fakturabeløb_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afgiftsanmeldelse',
            options={'ordering': ['status', 'dato']},
        ),
        migrations.AlterField(
            model_name='afgiftsanmeldelse',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ny'), (2, 'afvist'), (3, 'godkendt'), (4, 'afsluttet')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalafgiftsanmeldelse',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ny'), (2, 'afvist'), (3, 'godkendt'), (4, 'afsluttet')], default=1),
        ),
    ]
