# Generated by Django 4.2.11 on 2024-10-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0014_toldkategorier'),
    ]

    operations = [
        migrations.AddField(
            model_name='afgiftsanmeldelse',
            name='tf3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalafgiftsanmeldelse',
            name='tf3',
            field=models.BooleanField(default=False),
        ),
    ]
