# Generated by Django 4.2.11 on 2025-08-22 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anmeldelse', '0016_toldkategorier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afgiftsanmeldelse',
            name='oprettet_af',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afgiftsanmeldelser', to=settings.AUTH_USER_MODEL),
        ),
    ]
