# Generated by Django 4.2.11 on 2025-07-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0016_toldkategorier'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='varelinje',
            name='aktuel_har_vareafgiftssats',
        ),
        migrations.RemoveField(
            model_name='historicalvarelinje',
            name='kladde',
        ),
        migrations.RemoveField(
            model_name='varelinje',
            name='kladde',
        ),
    ]
