# Generated by Django 4.2.11 on 2025-09-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0017_alter_afgiftsanmeldelse_oprettet_af'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afgiftsanmeldelse',
            name='status',
            field=models.CharField(choices=[('kladde', 'kladde'), ('ny', 'ny'), ('afvist', 'afvist'), ('godkendt', 'godkendt'), ('afsluttet', 'afsluttet'), ('slettet', 'slettet')], default='ny'),
        ),
        migrations.AlterField(
            model_name='historicalafgiftsanmeldelse',
            name='status',
            field=models.CharField(choices=[('kladde', 'kladde'), ('ny', 'ny'), ('afvist', 'afvist'), ('godkendt', 'godkendt'), ('afsluttet', 'afsluttet'), ('slettet', 'slettet')], default='ny'),
        ),
        migrations.AlterField(
            model_name='historicalprivatafgiftsanmeldelse',
            name='status',
            field=models.CharField(choices=[('ny', 'ny'), ('annulleret', 'annulleret'), ('afvist', 'afvist'), ('godkendt', 'godkendt'), ('afsluttet', 'afsluttet'), ('slettet', 'slettet')], default='ny'),
        ),
        migrations.AlterField(
            model_name='privatafgiftsanmeldelse',
            name='status',
            field=models.CharField(choices=[('ny', 'ny'), ('annulleret', 'annulleret'), ('afvist', 'afvist'), ('godkendt', 'godkendt'), ('afsluttet', 'afsluttet'), ('slettet', 'slettet')], default='ny'),
        ),
    ]
