# Generated by Django 4.2.24 on 2025-10-08 07:46

from django.db import migrations, models

def populate_indførselstilladelser(apps, schema_editor):
    Afgitsanmeldelse = apps.get_model('anmeldelse', 'Afgiftsanmeldelse')
    HistoricalAfgiftsanmeldelse = apps.get_model(
        'anmeldelse',
        'HistoricalAfgiftsanmeldelse',
    )
    for afgiftsanmeldelse in Afgiftsanmeldelse.objects.all():
        afgiftsanmeldelse.indførselstilladelse_alkohol = afgiftsanmeldelse.indførselstilladelse
        afgiftsanmeldelse.indførselstilladelse_tobak = afgiftsanmeldelse.indførselstilladelse
        afgiftsanmeldelse.save()
    for historicalafgiftsanmeldelse in HistoricalAfgiftsanmeldelse.objects.all():
        historicalafgiftsanmeldelse.indførselstilladelse_alkohol = historicalafgiftsanmeldelse.indførselstilladelse
        historicalafgiftsanmeldelse.indførselstilladelse_tobak = historicalafgiftsanmeldelse.indførselstilladelse
        historicalafgiftsanmeldelse.save()

class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0018_alter_afgiftsanmeldelse_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afgiftsanmeldelse',
            name='indførselstilladelse_alkohol',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='afgiftsanmeldelse',
            name='indførselstilladelse_tobak',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalafgiftsanmeldelse',
            name='indførselstilladelse_alkohol',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalafgiftsanmeldelse',
            name='indførselstilladelse_tobak',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.RunPython(populate_indførselstilladelser),
        migrations.RemoveField(
            model_name='afgiftsanmeldelse',
            name='indførselstilladelse',
        ),
        migrations.RemoveField(
            model_name='historicalafgiftsanmeldelse',
            name='indførselstilladelse',
        ),
    ]
