# Generated by Django 4.2.24 on 2025-11-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldelse', '0019_remove_afgiftsanmeldelse_indførselstilladelse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afgiftsanmeldelse',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalafgiftsanmeldelse',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalprivatafgiftsanmeldelse',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='privatafgiftsanmeldelse',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
