# Generated by Django 4.2.2 on 2024-02-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('nets', 'Nets'), ('bank', 'Bankoverførsel')], default='nets', max_length=128),
        ),
    ]
